# Generated by Django 4.2.30 on 2026-06-24 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['coordinator'], name='organizatio_coordin_d09e09_idx'),
        ),
    ]
