# Generated by Django 4.2.30 on 2026-06-24 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_department_coordinator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_role', models.CharField(choices=[('LEADER', 'Leader'), ('ASSISTANT_LEADER', 'Assistant Leader'), ('MEMBER', 'Member')], default='MEMBER', max_length=30)),
                ('member_type', models.CharField(choices=[('MAIN', 'Main'), ('MIX', 'Mix')], default='MAIN', max_length=10)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['team'], name='organizatio_team_id_dcc454_idx'), models.Index(fields=['user'], name='organizatio_user_id_4d84a7_idx'), models.Index(fields=['team_role'], name='organizatio_team_ro_e1f06c_idx'), models.Index(fields=['member_type'], name='organizatio_member__24cc1d_idx'), models.Index(fields=['is_active'], name='organizatio_is_acti_c8596e_idx'), models.Index(fields=['deleted_at'], name='organizatio_deleted_0a0300_idx')],
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='TODO', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organization.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team'], name='organizatio_team_id_aefde0_idx'), models.Index(fields=['assigned_to'], name='organizatio_assigne_a080fe_idx'), models.Index(fields=['assigned_by'], name='organizatio_assigne_04af02_idx'), models.Index(fields=['status'], name='organizatio_status_2e1c3e_idx'), models.Index(fields=['priority'], name='organizatio_priorit_197d9b_idx'), models.Index(fields=['due_date'], name='organizatio_due_dat_a9baad_idx'), models.Index(fields=['deleted_at'], name='organizatio_deleted_ee7776_idx')],
            },
        ),
    ]
