# Generated by Django 4.2.30 on 2026-06-24 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0003_teammember_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('meeting_type', models.CharField(choices=[('ORG', 'Organization'), ('DEPARTMENT', 'Department'), ('TEAM', 'Team')], default='TEAM', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_calendar_link', models.URLField(blank=True, null=True)),
                ('is_synced_google', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='organization.department')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='organization.team')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('achievement_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_achievements', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='organization.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achievement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ATTENDED', 'Attended'), ('ABSENT', 'Absent')], default='INVITED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='organization.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['meeting'], name='organizatio_meeting_911e4c_idx'), models.Index(fields=['user'], name='organizatio_user_id_0e1f84_idx'), models.Index(fields=['status'], name='organizatio_status_fb884b_idx')],
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_type'], name='organizatio_meeting_7988db_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['department'], name='organizatio_departm_e08362_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['team'], name='organizatio_team_id_9ed880_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['created_by'], name='organizatio_created_6d370e_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['start_datetime'], name='organizatio_start_d_21a8d2_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['deleted_at'], name='organizatio_deleted_04f33b_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['user'], name='organizatio_user_id_fa52c5_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['team'], name='organizatio_team_id_080dad_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['created_by'], name='organizatio_created_897788_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['achievement_date'], name='organizatio_achieve_6f2148_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['deleted_at'], name='organizatio_deleted_633879_idx'),
        ),
    ]
