# Generated by Django 4.2.30 on 2026-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_avatar_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('LEADER', 'Leader'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='usercontact',
            index=models.Index(fields=['user'], name='authenticat_user_id_f5aced_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontact',
            index=models.Index(fields=['contact_type'], name='authenticat_contact_5e7fa3_idx'),
        ),
    ]
