# Generated by Django 4.2.30 on 2026-06-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_managers_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercontact',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercontact',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username (e.g. @username)', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['user'], name='authenticat_user_id_dc3568_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['otp'], name='authenticat_otp_72ec8d_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['created_at'], name='authenticat_created_1b0979_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='authenticat_email_d74434_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='authenticat_role_7fb088_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='authenticat_status_35d44c_idx'),
        ),
        migrations.DeleteModel(
            name='UserContact',
        ),
    ]
